apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
{{ include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
{{ include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
{{ include "labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.appName }}
{{ include "create_container" . | indent 10 }}
          ports:
            - containerPort: {{ .Values.appPort }}
              name: app-port
          livenessProbe:
            httpGet:
              path: /alive
              port: app-port
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: app-port
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
{{ include "create_env" . | indent 12 }}