apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: anfa.ml
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: {{ .Values.appPort }}
