apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: anfa.ml
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: {{ .Values.appPort }}
  tls:
  - hosts:
      - "anfa.ml"
    secretName: anfa-ml-tls