apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.REDIS_SVC_NAME }}
{{ include "labels" . | indent 2 }}
spec:
  serviceName: {{ .Values.REDIS_SVC_NAME }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.REDIS_SVC_NAME }}
    spec:
      containers:
      - name: {{ .Values.REDIS_SVC_NAME }}
        image: redis:4.0.5-alpine
        ports:
        - containerPort: 6379
          name: {{ .Values.REDIS_SVC_NAME }}
        volumeMounts:
        - mountPath: "/data"
          name: anfa-redis-persistent-storage
        - mountPath: "/secrets"
          name: demo-config
      volumes:
        - name: demo-config
          configMap:
            name: demo-cfg
            items:
              - key: game.properties
                path: game.properties
  volumeClaimTemplates:
  - metadata:
      name: anfa-redis-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: 'standard'
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.REDIS_SVC_NAME }}
{{ include "labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Values.REDIS_SVC_NAME }}
  type: {{ .Values.service.type }}
  ports:
  - port: 6379
    protocol: TCP

