apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.appName }}
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.appPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.appName }}