apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{default "Always" .Values.image.pullPolicy}}
          ports:
          - containerPort: {{ .Values.appPort }}